<script lang="ts" context="module">
	import { website } from '$config/website.js';
	import { projectStructure } from '$data/structure.js';
	import type { IWebPageMetadata } from '@sveltinio/seo/types';
	import { OpenGraphType, TwitterCardType } from '@sveltinio/seo/types';
	import { PageMetaTags, JsonLdWebPage, JsonLdBreadcrumbs } from '@sveltinio/seo';
	import { getFavicon, getPageUrl } from '$lib/utils/strings.js';

	const appStructurePage: IWebPageMetadata = {
		url: getPageUrl('project-structure', website),
		title: 'Sveltin Project Structure',
		description: 'Here you can learn about the Project Structure for a Sveltin based website.',
		keywords: website.keywords,
		image: getFavicon(website),
		opengraph: {
			type: OpenGraphType.Article
		},
		twitter: {
			type: TwitterCardType.Summary
		}
	};
</script>

<PageMetaTags data={appStructurePage} />
<JsonLdWebPage data={appStructurePage} />
<JsonLdBreadcrumbs baseURL={website.baseURL} parent="" currentTitle={appStructurePage.title} />

<!-- PAGE TITLE-->
<section
	class="mx-auto max-w-7xl border-b border-skin-muted bg-skin-light dark:border-skin-muted-dark dark:bg-skin-dark"
>
	<div class="mx-auto max-w-7xl px-4 pt-20 sm:px-6 md:px-32 lg:pt-44">
		<h1
			class="mx-auto py-2 text-4xl font-light leading-none tracking-tighter text-skin-heading dark:text-skin-heading-dark lg:py-10 lg:text-5xl"
		>
			{appStructurePage.title}
		</h1>
	</div>
</section>
<!-- END OF PAGE TITLE-->
<!-- PAGE CONTENT -->
<section class="bg-skin-light pt-6 pb-24 dark:bg-skin-dark">
	<div class="mx-auto px-4 sm:px-6 md:px-32">
		<section>
			<div class="max-w-3xl">
				<div class="mx-auto space-y-24 text-left text-lg">
					<div class="space-y-4">
						<p
							class="text-base font-light text-skin-body dark:text-skin-body-dark sm:text-lg"
						>
							Sveltin uses a set of conventions over configuration to simplify the
							expirience without losing flexibility and don't repeat yourself.
						</p>
						<p
							class="text-base font-light text-skin-body dark:text-skin-body-dark sm:text-lg"
						>
							A Sveltin app will have a number of generated files and folders that
							make up the structure of the project. Here is a basic rundown on the
							function of each of the files and folders Sveltin creates by default.
						</p>
						<p
							class="text-base font-light text-skin-body dark:text-skin-body-dark sm:text-lg"
						>
							A Sveltin project looks like this:
						</p>
						<pre><code class="prose text-slate-800">
my-project/
 ├ config/
 │ └ [autogenerated and your own config files]
 ├ content/
 │ └ [your markdown files]
 ├ src/
 │ ├ lib/
 │ │ └ [autogenerated and your own files]
 │ ├ params/
 │ │ └ [autogenerated and your own matchers]
 │ ├ routes/
 │ │ └ api
 │ │ │ └ [autogenerated]
 │ │ └ [autogenerated and your own routes]
 │ ├ app.html
 │ ├ app.css
 ├ static/
 │ └ [your static assets]
 ├ themes/
 │ └ [autogenerated]
 │ │ └ [your components and partials]
 ├ package.json
 ├ svelte.config.js
 ├ tsconfig.json
 └ vite.config.ts
						</code></pre>

						<div class="flex flex-col">
							<div class="-my-2 overflow-x-auto  sm:-mx-6 lg:-mx-8">
								<div
									class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8"
								>
									<h2
										class="py-6 text-lg font-normal text-skin-heading hover:text-skin-heading-hover dark:text-skin-heading-dark lg:text-2xl"
									>
										Project folders and files
									</h2>
									<div
										class="overflow-hidden border-b border-gray-200 shadow dark:border-gray-500 sm:rounded-lg"
									>
										<table
											class="min-w-full divide-y divide-gray-200 dark:divide-gray-500"
										>
											<thead
												class="bg-gray-50 dark:border-gray-300 dark:bg-skin-base-dark"
											>
												<tr>
													<th
														scope="col"
														class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-skin-body-dark"
													>
														File/Folder
													</th>
													<th
														scope="col"
														class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-skin-body-dark"
													>
														Purpose
													</th>
												</tr>
											</thead>
											<tbody>
												{#each projectStructure as f}
													<!-- Even row -->
													<tr class="bg-skin-light dark:bg-skin-dark">
														<td
															class="whitespace-nowrap px-6 py-4 text-sm font-medium text-gray-900 dark:text-skin-body-dark"
														>
															{f.name}
														</td>
														<td
															class="whitespace-nowrap px-6 py-4 text-sm text-skin-body dark:text-skin-body-dark"
														>
															{@html f.purpose}
														</td>
													</tr>
												{/each}
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</section>
<!-- END OF PAGE CONTENT -->
