name: Deploy
on:
  push:
    branches: [stable]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install --location=global pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm build
        env:
          VITE_PUBLIC_BASE_PATH: https://docs.sveltin.io

      - name: FTP Deploy to production domain
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.PROD_FTP_HOSTNAME }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          dry-run: false
          local-dir: ./build/
          server-dir: ${{ secrets.PROD_FTP_SERVER_FOLDER }}
          exclude: .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
